name: haskell-awk
version: 0.1.0.0

extra-source-files:
- README.md
- LICENSE

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - array
  - base
  - bytestring
  build-tools:
  - alex
  - happy

executables:
  awk:
    main: app/Main.hs
    dependencies:
    - base
    - bytestring
    - haskell-awk